version: '3.2'

services:
  integration_tests:
    image: $LOCAL_IMAGE_ID

    # We are setting "/usr/src/testdir" as current directory
    # to not manipulate the image contents with testing elements.
    volumes:
      - ./test/:/app/test/

    tty: false
    command: >
      sh -c "apk --no-cache --virtual build-dependencies add \
            git \
            python \
            make \
            && npm install \
            && npm run test:integration"
