version: '3.2'

services:
  integration_tests:
    build: .
    image: $LOCAL_IMAGE_ID
    tty: false
    command: >
      sh -c "apk add openssl git python make &&
             npm ci && \
             npm run test:integration"
